@URL = http://localhost:8080/person

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjBlNDU4NmNiLTc1OGYtNDUzMC1hMTM3LTYyZTM0NzU1MjU5OSIsInVzZXJuYW1lIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNzMwNDA0NTAyLCJleHAiOjE3MzA0MDgxMDIsImlzcyI6IlVURlBSIn0.MdY8vtU-apg1mJw1sxSrp5TSoik4Mt_QP1NJxlR4sZE


### Obter todas pessoas
GET {{URL}}
Authorization: {{token}}

### Obter uma pessoa pelo ID
GET {{URL}}/70572e7b-0db0-4b20-8fd3-6c74ef4c1706
Authorization: {{token}}

### Criar uma pessoa
POST {{URL}}
Content-Type: application/json

{
    "name": "Julia",
    "email": "julia@gmail.com",
    "password": "1234",
    "birth": "2000-05-05"
}

### Atualizar uma pessoa
PUT {{URL}}/1520a44d-363e-4e31-b08b-2090dd395d0b
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Marcelo",
    "email": "mar@gmail.com",
    "username": "mar",
    "password": "1234",
    "birth": "2000-05-06"
}


### Deletar uma pessoa
DELETE {{URL}}/85bd872e-9017-4c5e-a218-446352253490
Authorization: {{token}}